import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { Footer } from "@/components/common/footer";

import "./globals.css";
import { Gnb } from "@/components/common/gnb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "haesoo's blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Gnb />
        {children}
        <Footer />
      </body>
    </html>
  );
}
